export interface SeedQuestion {
  category: string;
  text: string;
  options: string[];
  correctIndex: number;
  /** يمنع ظهور أكثر من صياغة لنفس المعلومة في الجولات */
  familyKey?: string;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ============ أدب ============
  { category: "adab", text: "من هو الشاعر الملقب بـ«أمير الشعراء»؟", options: ["أحمد شوقي", "حافظ إبراهيم", "المتنبي", "نزار قباني"], correctIndex: 0 },
  { category: "adab", text: "من مؤلف كتاب «الأيام»؟", options: ["طه حسين", "توفيق الحكيم", "نجيب محفوظ", "العقاد"], correctIndex: 0 },
  { category: "adab", text: "من صاحب رواية «أولاد حارتنا»؟", options: ["نجيب محفوظ", "يوسف إدريس", "إحسان عبد القدوس", "جمال الغيطاني"], correctIndex: 0 },
  { category: "adab", text: "من هو الشاعر الملقب بـ«شاعر النيل»؟", options: ["حافظ إبراهيم", "أحمد شوقي", "محمود سامي البارودي", "إيليا أبو ماضي"], correctIndex: 0 },
  { category: "adab", text: "من صاحب رواية «البؤساء»؟", options: ["فيكتور هوغو", "تولستوي", "دوستويفسكي", "تشيخوف"], correctIndex: 0 },
  { category: "adab", text: "من هو مترجم كتاب «كليلة ودمنة» إلى العربية؟", options: ["ابن المقفع", "الجاحظ", "ابن خلدون", "المتنبي"], correctIndex: 0 },
  { category: "adab", text: "من هو الشاعر الجاهلي صاحب معلقة «قفا نبكِ»؟", options: ["امرؤ القيس", "عنترة بن شداد", "زهير بن أبي سلمى", "لبيد"], correctIndex: 0 },
  { category: "adab", text: "من صاحب كتاب «البخلاء»؟", options: ["الجاحظ", "ابن المقفع", "أبو حيان التوحيدي", "ابن قتيبة"], correctIndex: 0 },
  { category: "adab", text: "من هو الكاتب العربي الحائز على جائزة نوبل في الأدب؟", options: ["نجيب محفوظ", "طه حسين", "توفيق الحكيم", "أدونيس"], correctIndex: 0 },
  { category: "adab", text: "من صاحب ديوان «الشوقيات»؟", options: ["أحمد شوقي", "حافظ إبراهيم", "خليل مطران", "البارودي"], correctIndex: 0 },
  { category: "adab", text: "من صاحب «رسالة الغفران»؟", options: ["أبو العلاء المعري", "ابن سينا", "الفارابي", "ابن رشد"], correctIndex: 0 },
  { category: "adab", text: "من صاحب كتاب «وحي القلم»؟", options: ["مصطفى صادق الرافعي", "المنفلوطي", "طه حسين", "العقاد"], correctIndex: 0 },
  { category: "adab", text: "من مؤلف «مقدمة ابن خلدون»؟", options: ["ابن خلدون", "ابن سينا", "ابن بطوطة", "ابن النفيس"], correctIndex: 0 },
  { category: "adab", text: "من صاحب كتاب «العبرات»؟", options: ["مصطفى لطفي المنفلوطي", "جبران خليل جبران", "ميخائيل نعيمة", "أمين الريحاني"], correctIndex: 0 },
  { category: "adab", text: "من صاحب رواية «السكرية»؟", options: ["نجيب محفوظ", "يوسف السباعي", "ثروت أباظة", "فتحي غانم"], correctIndex: 0 },
  { category: "adab", text: "من مؤلف كتاب «الأغاني»؟", options: ["أبو الفرج الأصفهاني", "ابن قتيبة", "المسعودي", "ابن هشام"], correctIndex: 0 },
  { category: "adab", text: "من هو الشاعر الملقب بـ«شاعر الشباب»؟", options: ["أحمد رامي", "إبراهيم ناجي", "علي محمود طه", "أبو القاسم الشابي"], correctIndex: 0 },
  { category: "adab", text: "من هو الشاعر صاحب معلقة «هل غادر الشعراء من متردم»؟", options: ["عنترة بن شداد", "امرؤ القيس", "زهير بن أبي سلمى", "النابغة الذبياني"], correctIndex: 0 },
  { category: "adab", text: "من هو الشاعر الملقب بـ«شاعر القطرين»؟", options: ["خليل مطران", "إيليا أبو ماضي", "بشارة الخوري", "ميخائيل نعيمة"], correctIndex: 0 },
  { category: "adab", text: "من صاحب رواية «قنديل أم هاشم»؟", options: ["يحيى حقي", "نجيب محفوظ", "طه حسين", "عبد الرحمن الشرقاوي"], correctIndex: 0 },
  { category: "adab", text: "من مؤلف رواية «الأرض»؟", options: ["عبد الرحمن الشرقاوي", "يوسف إدريس", "نجيب محفوظ", "إحسان عبد القدوس"], correctIndex: 0 },
  { category: "adab", text: "من هو الأديب الملقب بـ«عميد الأدب العربي»؟", options: ["طه حسين", "العقاد", "توفيق الحكيم", "أحمد أمين"], correctIndex: 0 },
  { category: "adab", text: "من صاحب قصيدة «نهج البردة»؟", options: ["أحمد شوقي", "البوصيري", "حافظ إبراهيم", "محمود سامي البارودي"], correctIndex: 0 },
  { category: "adab", text: "من هو الشاعر صاحب «لامية العرب»؟", options: ["الشنفرى", "تأبط شراً", "عروة بن الورد", "طرفة بن العبد"], correctIndex: 0 },

  // ============ علوم ============
  { category: "science", text: "كم عدد كواكب المجموعة الشمسية؟", options: ["8", "9", "7", "10"], correctIndex: 0 },
  { category: "science", text: "ما العنصر الأكثر وفرة في الغلاف الجوي للأرض؟", options: ["النيتروجين", "الأكسجين", "ثاني أكسيد الكربون", "الهيدروجين"], correctIndex: 0 },
  { category: "science", text: "ما أكبر كوكب في المجموعة الشمسية؟", options: ["المشتري", "زحل", "الأرض", "نبتون"], correctIndex: 0 },
  { category: "science", text: "ما العضو المسؤول عن ضخ الدم في جسم الإنسان؟", options: ["القلب", "الكبد", "الرئتان", "الكلى"], correctIndex: 0 },
  { category: "science", text: "كم عدد أسنان الإنسان البالغ؟", options: ["32", "28", "30", "36"], correctIndex: 0 },
  { category: "science", text: "ما الحيوان الملقب بـ«سفينة الصحراء»؟", options: ["الجمل", "الحصان", "الفيل", "الحمار"], correctIndex: 0 },
  { category: "science", text: "ما أقرب كوكب إلى الشمس؟", options: ["عطارد", "الزهرة", "الأرض", "المريخ"], correctIndex: 0 },
  { category: "science", text: "كم عدد عظام جسم الإنسان البالغ؟", options: ["206", "300", "150", "250"], correctIndex: 0 },
  { category: "science", text: "ما الغاز الذي تمتصه النباتات من الجو؟", options: ["ثاني أكسيد الكربون", "الأكسجين", "النيتروجين", "الهيدروجين"], correctIndex: 0 },
  { category: "science", text: "ما الكوكب الملقب بـ«الكوكب الأحمر»؟", options: ["المريخ", "المشتري", "الزهرة", "عطارد"], correctIndex: 0 },
  { category: "science", text: "ما وحدة قياس شدة التيار الكهربائي؟", options: ["الأمبير", "الفولت", "الواط", "الأوم"], correctIndex: 0 },
  { category: "science", text: "من اكتشف قانون الجاذبية؟", options: ["إسحاق نيوتن", "أينشتاين", "أرخميدس", "جاليليو"], correctIndex: 0 },
  { category: "science", text: "ما أسرع حيوان بري في العالم؟", options: ["الفهد", "الأسد", "الحصان", "الغزال"], correctIndex: 0 },
  { category: "science", text: "كم عدد ألوان قوس قزح؟", options: ["7", "6", "5", "8"], correctIndex: 0 },
  { category: "science", text: "ما أطول نهر في العالم؟", options: ["النيل", "الأمازون", "المسيسيبي", "الدانوب"], correctIndex: 0 },
  { category: "science", text: "ما أكبر محيطات العالم؟", options: ["الهادئ", "الأطلسي", "الهندي", "المتجمد"], correctIndex: 0 },
  { category: "science", text: "ما المعدن السائل في درجة حرارة الغرفة؟", options: ["الزئبق", "الحديد", "الذهب", "النحاس"], correctIndex: 0 },
  { category: "science", text: "ما أكبر عضو في جسم الإنسان؟", options: ["الجلد", "الكبد", "الدماغ", "الأمعاء"], correctIndex: 0 },
  { category: "science", text: "ما العضو الذي يفرز هرمون الأنسولين؟", options: ["البنكرياس", "الكبد", "المعدة", "الغدة الدرقية"], correctIndex: 0 },
  { category: "science", text: "كم عدد أرجل العنكبوت؟", options: ["8", "6", "10", "4"], correctIndex: 0 },
  { category: "science", text: "ما الرمز الكيميائي لعنصر الأكسجين؟", options: ["O", "Ox", "Og", "H"], correctIndex: 0 },
  { category: "science", text: "كم تستغرق الأرض لإكمال دورة كاملة حول نفسها؟", options: ["24 ساعة", "12 ساعة", "48 ساعة", "36 ساعة"], correctIndex: 0 },
  { category: "science", text: "ما الطائر الذي لا يستطيع الطيران؟", options: ["النعامة", "النسر", "الصقر", "اللقلق"], correctIndex: 0 },
  { category: "science", text: "ما الغاز الذي تحتاجه النار للاشتعال؟", options: ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيليوم"], correctIndex: 0 },

  // ============ إسلاميات ============
  { category: "islamiyat", text: "كم عدد أركان الإسلام؟", options: ["5", "4", "6", "7"], correctIndex: 0 },
  { category: "islamiyat", text: "كم عدد أركان الإيمان؟", options: ["6", "5", "7", "4"], correctIndex: 0 },
  { category: "islamiyat", text: "ما أول أركان الإسلام؟", options: ["الشهادتان", "الصلاة", "الزكاة", "الصوم"], correctIndex: 0 },
  { category: "islamiyat", text: "كم عدد الصلوات المفروضة في اليوم والليلة؟", options: ["5", "3", "6", "4"], correctIndex: 0 },
  { category: "islamiyat", text: "في أي شهر يصوم المسلمون؟", options: ["رمضان", "شعبان", "محرم", "رجب"], correctIndex: 0 },
  { category: "islamiyat", text: "ما هي القبلة الأولى للمسلمين؟", options: ["المسجد الأقصى", "الكعبة", "المسجد النبوي", "مسجد قباء"], correctIndex: 0 },
  { category: "islamiyat", text: "كم عدد ركعات صلاة الفجر؟", options: ["ركعتان", "ثلاث", "أربع", "خمس"], correctIndex: 0 },
  { category: "islamiyat", text: "ما السورة التي تعدل ثلث القرآن؟", options: ["الإخلاص", "الفلق", "الناس", "الكوثر"], correctIndex: 0 },
  { category: "islamiyat", text: "كم مرة يجب الحج على المسلم في العمر؟", options: ["مرة واحدة", "مرتين", "كل عام", "خمس مرات"], correctIndex: 0 },
  { category: "islamiyat", text: "من هو المَلَك المكلف بنزول الوحي؟", options: ["جبريل", "ميكائيل", "إسرافيل", "عزرائيل"], correctIndex: 0 },
  { category: "islamiyat", text: "من هو ملك الموت؟", options: ["عزرائيل", "جبريل", "ميكائيل", "إسرافيل"], correctIndex: 0 },
  { category: "islamiyat", text: "ما أول مسجد بُني في الإسلام؟", options: ["قباء", "النبوي", "الحرام", "الأقصى"], correctIndex: 0 },
  { category: "islamiyat", text: "ما المسجد الذي أُسري بالنبي ﷺ إليه؟", options: ["الأقصى", "قباء", "القبلتين", "النبوي"], correctIndex: 0 },
  { category: "islamiyat", text: "من هي أولى زوجات النبي ﷺ؟", options: ["خديجة", "عائشة", "حفصة", "سودة"], correctIndex: 0 },
  { category: "islamiyat", text: "ما السورة التي تسمى «قلب القرآن»؟", options: ["يس", "الرحمن", "الواقعة", "الملك"], correctIndex: 0 },
  { category: "islamiyat", text: "ما السورة التي تسمى «عروس القرآن»؟", options: ["الرحمن", "يس", "الدخان", "ق"], correctIndex: 0 },
  { category: "islamiyat", text: "كم عدد التكبيرات في الركعة الأولى من صلاة العيد؟", options: ["7", "5", "6", "3"], correctIndex: 0 },
  { category: "islamiyat", text: "ما معنى الإحسان؟", options: ["أن تعبد الله كأنك تراه", "أن تصلي في المسجد", "أن تصوم الاثنين والخميس", "أن تكثر من الصدقة"], correctIndex: 0 },
  { category: "islamiyat", text: "في أي شهر تكون ليلة القدر؟", options: ["رمضان", "شعبان", "رجب", "ذو الحجة"], correctIndex: 0 },
  { category: "islamiyat", text: "في أي شهر يقف الحجاج بعرفة؟", options: ["ذو الحجة", "شوال", "رمضان", "محرم"], correctIndex: 0 },
  { category: "islamiyat", text: "ما أول ما يُحاسب عليه العبد يوم القيامة؟", options: ["الصلاة", "الصيام", "الزكاة", "بر الوالدين"], correctIndex: 0 },
  { category: "islamiyat", text: "من هو النبي الذي ابتلعه الحوت؟", options: ["يونس", "موسى", "يوسف", "هود"], correctIndex: 0 },
  { category: "islamiyat", text: "ما السورة التي تسمى «المنجية»؟", options: ["الملك", "يس", "الواقعة", "الدخان"], correctIndex: 0 },
  { category: "islamiyat", text: "كم عدد التكبيرات في صلاة الجنازة؟", options: ["4", "3", "5", "2"], correctIndex: 0 },

  // ============ قرآن ============
  { category: "quran", text: "كم عدد سور القرآن الكريم؟", options: ["114", "113", "116", "120"], correctIndex: 0 },
  { category: "quran", text: "ما أطول سورة في القرآن؟", options: ["البقرة", "آل عمران", "النساء", "الأعراف"], correctIndex: 0 },
  { category: "quran", text: "ما أقصر سورة في القرآن؟", options: ["الكوثر", "العصر", "الإخلاص", "الناس"], correctIndex: 0 },
  { category: "quran", text: "كم عدد أجزاء القرآن؟", options: ["30", "29", "60", "20"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي لا تبدأ بالبسملة؟", options: ["التوبة", "الفاتحة", "البقرة", "النمل"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي وردت فيها البسملة مرتين؟", options: ["النمل", "التوبة", "الفاتحة", "هود"], correctIndex: 0 },
  { category: "quran", text: "ما أول سورة في ترتيب المصحف؟", options: ["الفاتحة", "البقرة", "العلق", "الناس"], correctIndex: 0 },
  { category: "quran", text: "ما آخر سورة نزلت من القرآن؟", options: ["النصر", "الإخلاص", "المائدة", "الفاتحة"], correctIndex: 0 },
  { category: "quran", text: "كم عدد سجدات التلاوة في القرآن؟", options: ["15", "10", "14", "20"], correctIndex: 0 },
  { category: "quran", text: "من هو النبي الأكثر ذكراً في القرآن؟", options: ["موسى", "إبراهيم", "عيسى", "نوح"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي تعدل نصف القرآن؟", options: ["الزلزلة", "الإخلاص", "الفاتحة", "يس"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي تسمى «أم الكتاب»؟", options: ["الفاتحة", "البقرة", "يس", "الملك"], correctIndex: 0 },
  { category: "quran", text: "كم عدد آيات سورة الفاتحة؟", options: ["7", "6", "8", "5"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي اسمها اسم حشرة؟", options: ["النمل", "الفيل", "القمر", "الشمس"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي اسمها اسم فاكهة؟", options: ["التين", "الرمان", "التفاح", "البرتقال"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي اسمها اسم معدن؟", options: ["الحديد", "الذهب", "الفضة", "النحاس"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي تسمى «سورة النساء الصغرى»؟", options: ["الطلاق", "النساء", "المجادلة", "الممتحنة"], correctIndex: 0 },
  { category: "quran", text: "من هو النبي الذي كلمه الله تكليماً؟", options: ["موسى", "إبراهيم", "عيسى", "آدم"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي تبدأ بقوله تعالى «تبارك الذي بيده الملك»؟", options: ["الملك", "يس", "الرحمن", "الواقعة"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي ذُكر اسم الله في كل آية منها؟", options: ["المجادلة", "البقرة", "آل عمران", "النساء"], correctIndex: 0 },
  { category: "quran", text: "كم مرة ذُكر اسم النبي محمد ﷺ في القرآن؟", options: ["4 مرات", "5", "3", "10"], correctIndex: 0 },
  { category: "quran", text: "ما أول ما نزل من القرآن؟", options: ["اقرأ (العلق)", "الفاتحة", "المدثر", "المزمل"], correctIndex: 0 },
  { category: "quran", text: "ما السورة التي تسمى «براءة»؟", options: ["التوبة", "الأنفال", "الحشر", "الممتحنة"], correctIndex: 0 },
  { category: "quran", text: "كم عدد السور التي تبدأ بالحروف «الم»؟", options: ["6", "5", "7", "4"], correctIndex: 0 },

  // ============ مسلسلات وأفلام عربية ============
  { category: "arabic-tv", text: "ما اسم المسلسل الشامي الشهير الذي تدور أحداثه في حارة دمشقية؟", options: ["باب الحارة", "طوق البنات", "أهل الغرام", "الهيبة"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطلا مسلسل «طاش ما طاش»؟", options: ["ناصر القصبي وعبدالله السدحان", "محمد العلي وراشد الشمراني", "فهد الحيان وخالد سامي", "عبدالعزيز المبدل وياسر السقاف"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «إسماعيلية رايح جاي»؟", options: ["محمد هنيدي", "أحمد حلمي", "هاني رمزي", "كريم عبد العزيز"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «ليالي الحلمية»؟", options: ["يحيى الفخراني", "نور الشريف", "محمود عبد العزيز", "صلاح السعدني"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «الكيت كات»؟", options: ["محمود عبد العزيز", "عادل إمام", "أحمد زكي", "نور الشريف"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطلة فيلم «عفريتة هانم»؟", options: ["شادية", "سعاد حسني", "فاتن حمامة", "نادية لطفي"], correctIndex: 0 },
  { category: "arabic-tv", text: "من الفنان الملقب بـ«الزعيم»؟", options: ["عادل إمام", "أحمد زكي", "محمد صبحي", "نور الشريف"], correctIndex: 0 },
  { category: "arabic-tv", text: "من جسدت دور «أم كلثوم» في مسلسل أم كلثوم؟", options: ["صابرين", "عبلة كامل", "شريهان", "غادة عادل"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «الأسطورة»؟", options: ["محمد رمضان", "عمرو يوسف", "أحمد السقا", "أمير كرارة"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «مستر كاراتيه»؟", options: ["أحمد زكي", "محمود ياسين", "عادل إمام", "فاروق الفيشاوي"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «الناظر»؟", options: ["علاء ولي الدين", "محمد سعد", "هاني رمزي", "محمد هنيدي"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطلة فيلم «خلي بالك من زوزو»؟", options: ["سعاد حسني", "شادية", "نجلاء فتحي", "ميرفت أمين"], correctIndex: 0 },
  { category: "arabic-tv", text: "ما اسم المسلسل السوري الكوميدي الذي دارت أحداثه في قرية؟", options: ["ضيعة ضايعة", "أهل الراية", "يوم بيوم", "الغربال"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «الفيل الأزرق»؟", options: ["كريم عبد العزيز", "أحمد حلمي", "محمد إمام", "أحمد السقا"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «الاختيار» الذي جسد شخصية أحمد المنسي؟", options: ["أمير كرارة", "أحمد السقا", "محمد رمضان", "كريم عبد العزيز"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «عمر وسلمى»؟", options: ["تامر حسني", "أحمد حلمي", "محمد هنيدي", "كريم عبد العزيز"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «الكبير أوي»؟", options: ["أحمد مكي", "محمد إمام", "مصطفى خاطر", "أحمد أمين"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «جعفر العمدة»؟", options: ["محمد رمضان", "عمرو سعد", "مصطفى شعبان", "أحمد العوضي"], correctIndex: 0 },
  { category: "arabic-tv", text: "من جسد شخصية «اللمبي»؟", options: ["محمد سعد", "علاء ولي الدين", "أحمد حلمي", "سعد الصغير"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «أبو العروسة»؟", options: ["ماجد المصري", "مصطفى قمر", "ممدوح عبد العليم", "خالد النبوي"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل فيلم «إكس لارج»؟", options: ["أحمد حلمي", "محمد هنيدي", "هاني رمزي", "كريم محمود عبد العزيز"], correctIndex: 0 },
  { category: "arabic-tv", text: "من بطل مسلسل «العاصوف»؟", options: ["ناصر القصبي", "عبدالله السدحان", "راشد الشمراني", "حبيب الحبيب"], correctIndex: 0 },

  // ============ كرتون سبيستون ============
  { category: "spacetoon", text: "ما اسم بطل كرتون «كابتن ماجد»؟", options: ["ماجد", "سعد", "ياسر", "وليد"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الفريق الذي يلعب فيه كابتن ماجد؟", options: ["الهلال", "النصر", "الشباب", "الاتحاد"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم المحقق الصغير في كرتون سبيستون؟", options: ["كونان", "كين", "شينشي", "داي"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم صديقة المحقق كونان؟", options: ["ران", "سونوكو", "هايبرا", "ميا"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون المقتبس من رواية «بدون عائلة»؟", options: ["ريمي", "كونان", "عدنان", "توم سوير"], correctIndex: 0 },
  { category: "spacetoon", text: "من هو قائد الآلة العملاقة «غريندايزر»؟", options: ["دوق فليد", "غران", "كابتن ماجد", "لوفي"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم كرتون سبيستون عن كرة السلة؟", options: ["سلام دانك", "كابتن ماجد", "الشجعان", "أبطال الديجيتال"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون الذي تدور أحداثه عن صبي في عالم ما بعد الكارثة؟", options: ["فتى المستقبل كونان", "ريمي", "هيزل", "ساندي بل"], correctIndex: 0 },
  { category: "spacetoon", text: "من هو بطل كرتون «دراغون بول»؟", options: ["غوكو", "فيجيتا", "كريلين", "بيكولو"], correctIndex: 0 },
  { category: "spacetoon", text: "من هو بطل كرتون «ون بيس»؟", options: ["لوفي", "ناروتو", "زورو", "سانجي"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم كرتون سبيستون عن أطفال يدخلون عالم الديجيتال؟", options: ["أبطال الديجيتال", "المحقق كونان", "يوغي", "إينوياشا"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون عن فتاة نبيلة تتنكر بزي رجل؟", options: ["ليدي أوسكار", "ساندي بل", "نوار", "ريمي"], correctIndex: 0 },
  { category: "spacetoon", text: "من هو بطل كرتون «يوغي»؟", options: ["يوغي", "كايبا", "جوي", "باكورا"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم كرتون سبيستون عن مغامرات سنجاب؟", options: ["بندق", "فرفور", "سنوبي", "جيري"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون الذي يروي قصص الأنبياء؟", options: ["قصص الأنبياء", "حكايات عالمية", "رحلة النخبة", "أساطير من التاريخ"], correctIndex: 0 },
  { category: "spacetoon", text: "من هو بطل كرتون «داي الشجاع»؟", options: ["داي", "بوب", "ران", "هيون"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم كرتون سبيستون عن الآليين المتحولين؟", options: ["المتحولون", "غريندايزر", "الرجل الحديدي", "أبطال الديجيتال"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم كرتون سبيستون عن فرقة أطفال مغامرين؟", options: ["المغامرون الخمسة", "الشجعان الخمسة", "أبطال الكرة", "فرسان الأرض"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون الذي تتحول فيه البطلة إلى حورية بحر؟", options: ["ساندي بل", "ليدي أوسكار", "أليس", "نوار"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون عن الفتاة «هايدي» التي عاشت عند جدها؟", options: ["هايدي", "ريمي", "نوار", "ساندي"], correctIndex: 0 },
  { category: "spacetoon", text: "من هو بطل كرتون «قبطان فيكتور»؟", options: ["فيكتور", "بوب", "ران", "مارك"], correctIndex: 0 },
  { category: "spacetoon", text: "ما اسم الكرتون الذي تدور أحداثه حول فتاة صغيرة اسمها «نوار»؟", options: ["نوار", "هايدي", "ساندي", "ريمي"], correctIndex: 0 },

  // ============ الصحابة والأنبياء ============
  { category: "companions", text: "من هو أول الخلفاء الراشدين؟", options: ["أبو بكر الصديق", "عمر بن الخطاب", "عثمان بن عفان", "علي بن أبي طالب"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الملقب بـ«الفاروق»؟", options: ["عمر بن الخطاب", "أبو بكر الصديق", "عثمان بن عفان", "طلحة بن عبيد الله"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الملقب بـ«أمين الأمة»؟", options: ["أبو عبيدة بن الجراح", "خالد بن الوليد", "الزبير بن العوام", "سعد بن أبي وقاص"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الملقب بـ«ذي النورين»؟", options: ["عثمان بن عفان", "علي بن أبي طالب", "عثمان بن مظعون", "عبد الرحمن بن عوف"], correctIndex: 0 },
  { category: "companions", text: "من هو ابن عم النبي ﷺ وزوج ابنته؟", options: ["علي بن أبي طالب", "جعفر بن أبي طالب", "حمزة بن عبد المطلب", "العباس بن عبد المطلب"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الملقب بـ«أسد الله»؟", options: ["حمزة بن عبد المطلب", "خالد بن الوليد", "علي بن أبي طالب", "الزبير بن العوام"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الملقب بـ«سيف الله المسلول»؟", options: ["خالد بن الوليد", "أبو عبيدة بن الجراح", "عمرو بن العاص", "المثنى بن حارثة"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الملقب بـ«ترجمان القرآن»؟", options: ["عبد الله بن عباس", "عبد الله بن مسعود", "أبي بن كعب", "زيد بن ثابت"], correctIndex: 0 },
  { category: "companions", text: "من هو الصحابي الذي اهتز لموته عرش الرحمن؟", options: ["سعد بن معاذ", "سعد بن أبي وقاص", "مصعب بن عمير", "حمزة بن عبد المطلب"], correctIndex: 0 },
  { category: "companions", text: "من هو أول من أسلم من الرجال؟", options: ["أبو بكر الصديق", "علي بن أبي طالب", "زيد بن حارثة", "عمر بن الخطاب"], correctIndex: 0 },
  { category: "companions", text: "من هو أول من أسلم من الصبيان؟", options: ["علي بن أبي طالب", "عبد الله بن عباس", "أسامة بن زيد", "الحسن بن علي"], correctIndex: 0 },
  { category: "companions", text: "من هو أول من أسلم من الموالي؟", options: ["زيد بن حارثة", "بلال بن رباح", "صهيب الرومي", "سلمان الفارسي"], correctIndex: 0 },
  { category: "companions", text: "من هو أول من أسلم من النساء؟", options: ["خديجة بنت خويلد", "عائشة بنت أبي بكر", "فاطمة الزهراء", "أم سلمة"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي بنى السفينة؟", options: ["نوح", "موسى", "إبراهيم", "يونس"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي أُلقي في النار فلم تحرقه؟", options: ["إبراهيم", "إسماعيل", "يعقوب", "يوسف"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي آتاه الله ملكاً لا ينبغي لأحد من بعده؟", options: ["سليمان", "داود", "يوسف", "هارون"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي رُفع إلى السماء؟", options: ["عيسى", "إدريس", "يحيى", "زكريا"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الملقب بـ«كليم الله»؟", options: ["موسى", "عيسى", "إبراهيم", "نوح"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الملقب بـ«الذبيح»؟", options: ["إسماعيل", "إسحاق", "يعقوب", "يوسف"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي كان يعمل حداداً؟", options: ["داود", "سليمان", "نوح", "زكريا"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي وهبه الله ولداً على كبر؟", options: ["زكريا", "لوط", "هود", "صالح"], correctIndex: 0 },
  { category: "companions", text: "من هي أول شهيدة في الإسلام؟", options: ["سمية بنت خياط", "خديجة بنت خويلد", "فاطمة الزهراء", "أسماء بنت أبي بكر"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي أُرسل إلى قوم عاد؟", options: ["هود", "صالح", "شعيب", "لوط"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي أُرسل إلى قوم ثمود؟", options: ["صالح", "هود", "شعيب", "نوح"], correctIndex: 0 },
  { category: "companions", text: "من هو النبي الذي نزل عليه الزبور؟", options: ["داود", "موسى", "عيسى", "إبراهيم"], correctIndex: 0 },
];
